export { useLang } from './useLang';
export { useTheme } from './useTheme';
export { useSlider } from './useSlider';
export { usePreview } from './usePreview';
export { useHomePage } from './useHomePage';
export { useCurrentPage } from './useCurrentPage';
export { usePosts } from './usePosts';
export { useClients } from './useClients';
export { useNav } from './useNav';
